[LOCATION] [9.12.r1] Forwardport relevant commits from 8.1.r1
sonyxperiadev/vendor-qcom-opensource-location pull request #31
Opened 2021-02-12 18:59 UTC by kholk

This is a forward port of relevant commits from the old 8.1.r1 branch.
It also contains a fix for one of the reversed structs in the qmi headers.

Please note that on Android 11 this will fail with
error: libloc_loader: LOCAL_COPY_HEADERS is obsolete.

I know that somebody surely has it fixed locally (@MarijnS95 hello!),
so I'm not wasting time on this.

2021-02-12 20:57 UTC, kholk commented
This PR now builds fine and can be merged.

2021-02-12 22:24 UTC, MarijnS95 commented
> I know that somebody surely has it fixed locally (@MarijnS95 hello!), so I'm not wasting time on this.

Sorry to burst your bubble, but noupe, `-ENOTIME`!

Anyway this builds fine and instantly gives a bunch of satellites on PDX206 (that have previously been successfully acquired on 8.1 branches). Waiting for a fix now, but so far so good, thanks for sorting through that massive list of patches!

2021-02-12 22:50 UTC, MarijnS95 commented
And I just did something completely unholy, because my tree is currently set up for Edo/9.12/9.15 branches so I cannot build a clean vendor image for older devices. However, I can:

```console
$ adb shell rm /vendor/lib*/{libloc,libgps}*
$ m libloc_core libgps.utils liblocation_api libbatching libgeofencing libgnss libloc_api_v02 libgnsspps libsynergy_loc_api android.hardware.gnss@2.0-impl-qti
#### build completed successfully (50 seconds) ####
$ adb sync
/vendor/: 12 files pushed, 10 skipped. 9.9 MB/s (1715956 bytes in 0.166s)
$ adb root
```

The device just found one satellite, and `dumpsys location` shows them all. It usually takes a bit of time, but this indicates we're golden on older platforms, as expected because nothing changed API (nor blob) wise.

2021-02-12 23:00 UTC, MarijnS95 commented
Good news: Seine/PDX201 saw about ~10 sats and already has a fix, Edo/PDX206 is still trying to figure out whether to connect, with 43 known satellites :grimacing:

2021-02-12 23:10 UTC, MarijnS95 commented
And finally, Seine is now connected to 11 sats while Edo is connected to 8. All is working fine.

2021-02-13 11:44 UTC, ix5 requested changes

2021-02-13 11:44 UTC, ix5 commented on utils/loc_socket/Android.mk
>  ifeq ($(TARGET_KERNEL_VERSION),$(filter $(TARGET_KERNEL_VERSION),3.18 4.4 4.9))
Drop this whole commit, we're not using 4.9 kernels with this HAL

2021-02-15 07:27 UTC, merged